// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Devuelve la configuración para la web si es el caso
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Devuelve la configuración para Android
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Credenciales para la Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'apykey',
    authDomain: 'nfc-scanner-316c4.firebaseapp.com',
    projectId: 'nfc-scanner-316c4',
    storageBucket: 'nfc-scanner-316c4.appspot.com',
    messagingSenderId: '1065241435557',
    appId: '1:1065241435557:web:fb6be93cc71a173421dc4c',
  );

  // Credenciales para Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'apykey',
    appId: '1:1065241435557:android:ae82e6d1b878405421dc4c',
    messagingSenderId: '1065241435557',
    projectId: 'nfc-scanner-316c4',
    storageBucket: 'nfc-scanner-316c4.appspot.com',
  );
}
